# Generated by Django 5.1.5 on 2025-02-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=20)),
                ('course', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
            ],
        ),
    ]
